<a href="https://colab.research.google.com/github/SI-GRush34/beijing-air-quality-project/blob/main/Task1_Data_Selection_and_Handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Beijing Air Quality Analysis
## Task 1 – Data Selection and Handling

High concentrations of air pollutants like PM2.5, PM10, SO2, NO2, CO, and O3 can cause serious respiratory and cardiovascular diseases. Beijing, the capital city of :contentReference[oaicite:0]{index=0}, has had serious air pollution issues over the past 20 years due to rapid urbanisation, industrialisation, and rising vehicle emissions. The goal of this task is to select and integrate air quality datasets collected from monitoring stations in :contentReference[oaicite:1]{index=1}. Severe respiratory and cardiovascular conditions can result from high levels of air pollutants such PM2.5, PM10, SO2, NO2, CO, and O3. Over the past 20 years, increased urbanisation, industrialisation, and rising car emissions have caused serious air pollution issues in Beijing, the capital city of :contentReference[oaicite:0]{index=0}.

The selection and integration of air quality datasets gathered from monitoring stations in :contentReference[oaicite:1]{index=1} is the main goal of this assignment. The goal is to import, preprocess, and combine several datasets into a single, cohesive dataset that may be used for predictive modelling and additional exploratory data analysis.

## Importing Required Libraries

To facilitate data preprocessing, analysis, and visualisation chores, the following Python libraries were imported: Matplotlib and Seaborn are used for visualisation, while Pandas and NumPy are used for data manipulation and numerical calculations. Matplotlib and Seaborn are used for visualisation, while Pandas and NumPy are utilised for numerical computations and data manipulation.

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Monitoring Station Selection From the Beijing air quality monitoring network, two urban and two suburban monitoring stations were chosen for this analysis

From the Beijing air quality monitoring network, two urban and two suburban monitoring sites were chosen for this investigation:
Urban Stations: Dongsi and Guanyuan,
Suburban Stations: Changping and Huairou

Dongsi and Guanyuan were chosen as urban stations because they are situated in densely populated central regions of :contentReference[oaicite:2]{index=2}, where traffic congestion, commercial activity, and industrial emissions are relatively high. As a result, these locations are representative of inner-city pollution conditions. Changping and Huairou were chosen as suburban stations because they are located farther from the urban center and are characterised by lower population density and reduced industrial activity. These stations offer a useful comparison between urban and suburban air quality conditions. The categorisation was supported by earlier research, including studies by Xu & Zhang and Yao et al. As a result, these places are typical of pollution levels in inner cities.

Due to their distance from the city center, lower population density, and less industrial activity, Changping and Huairou were chosen as suburban stations. These stations offer a helpful comparison of the quality of the air in cities and suburbs.

Previous research, such as studies by Xu & Zhang and Yao et al., which categorise monitoring locations based on urban and suburban features, was used to support the station classification.

## Importing Selected Air Quality Datasets

The chosen datasets, which include hourly meteorological and air quality measurements gathered between March 2013 and February 2017, were uploaded into the Google Colab environment and imported using the Pandas library.

The Pandas library was used to import the chosen datasets after they were uploaded into the Google Colab environment. Hourly meteorological and air quality data from March 2013 to February 2017 are included in each file.

In [18]:
import os
os.listdir('/content')

['.config',
 'california_housing_test.csv',
 'mnist_test.csv',
 'PRSA_Data_Dongsi_20130301-20170228.csv',
 'PRSA_Data_Huairou_20130301-20170228.csv',
 'README.md',
 'PRSA_Data_Changping_20130301-20170228.csv',
 'sample_data',
 'mnist_train_small.csv',
 'PRSA_Data_Guanyuan_20130301-20170228.csv',
 'california_housing_train.csv',
 'anscombe.json']

In [21]:
import pandas as pd

dongsi = pd.read_csv('/content/PRSA_Data_Dongsi_20130301-20170228.csv')
guanyuan = pd.read_csv('/content/PRSA_Data_Guanyuan_20130301-20170228.csv')
changping = pd.read_csv('/content/PRSA_Data_Changping_20130301-20170228.csv')
huairou = pd.read_csv('/content/PRSA_Data_Huairou_20130301-20170228.csv')

print("All datasets loaded successfully!")

All datasets loaded successfully!

## Dataset Preview

The first 5 rows of the Dongsi monitoring station dataset are shown in the output that follows. This preview aids in confirming that the dataset has been successfully imported into the development environment.

In [24]:
# Display first 5 rows

print("Dongsi Dataset")
display(dongsi.head())

print("Guanyuan Dataset")
display(guanyuan.head())

print("Changping Dataset")
display(changping.head())

print("Huairou Dataset")
display(huairou.head())

print(dongsi.shape)

Dongsi Dataset

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,9.0,9.0,3.0,17.0,300.0,89.0,-0.5,1024.5,-21.4,0.0,NNW,5.7,Dongsi
1,2,2013,3,1,1,4.0,4.0,3.0,16.0,300.0,88.0,-0.7,1025.1,-22.1,0.0,NW,3.9,Dongsi
2,3,2013,3,1,2,7.0,7.0,NaN,17.0,300.0,60.0,-1.2,1025.3,-24.6,0.0,NNW,5.3,Dongsi
3,4,2013,3,1,3,3.0,3.0,5.0,18.0,NaN,NaN,-1.4,1026.2,-25.5,0.0,N,4.9,Dongsi
4,5,2013,3,1,4,3.0,3.0,7.0,NaN,200.0,84.0,-1.9,1027.1,-24.5,0.0,NNW,3.2,Dongsi

Guanyuan Dataset

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,14.0,20.0,300.0,69.0,-0.7,1023.0,-18.8,0.0,NNW,4.4,Guanyuan
1,2,2013,3,1,1,4.0,4.0,13.0,17.0,300.0,72.0,-1.1,1023.2,-18.2,0.0,N,4.7,Guanyuan
2,3,2013,3,1,2,3.0,3.0,10.0,19.0,300.0,69.0,-1.1,1023.5,-18.2,0.0,NNW,5.6,Guanyuan
3,4,2013,3,1,3,3.0,6.0,7.0,24.0,400.0,62.0,-1.4,1024.5,-19.4,0.0,NW,3.1,Guanyuan
4,5,2013,3,1,4,3.0,6.0,5.0,14.0,400.0,71.0,-2.0,1025.2,-19.5,0.0,N,2.0,Guanyuan

Changping Dataset

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,3.0,6.0,13.0,7.0,300.0,85.0,-2.3,1020.8,-19.7,0.0,E,0.5,Changping
1,2,2013,3,1,1,3.0,3.0,6.0,6.0,300.0,85.0,-2.5,1021.3,-19.0,0.0,ENE,0.7,Changping
2,3,2013,3,1,2,3.0,3.0,22.0,13.0,400.0,74.0,-3.0,1021.3,-19.9,0.0,ENE,0.2,Changping
3,4,2013,3,1,3,3.0,6.0,12.0,8.0,300.0,81.0,-3.6,1021.8,-19.1,0.0,NNE,1.0,Changping
4,5,2013,3,1,4,3.0,3.0,14.0,8.0,300.0,81.0,-3.5,1022.3,-19.4,0.0,N,2.1,Changping

Huairou Dataset

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,7.0,7.0,3.0,2.0,100.0,91.0,-2.3,1020.3,-20.7,0.0,WNW,3.1,Huairou
1,2,2013,3,1,1,4.0,4.0,3.0,NaN,100.0,92.0,-2.7,1020.8,-20.5,0.0,NNW,1.5,Huairou
2,3,2013,3,1,2,4.0,4.0,NaN,NaN,100.0,91.0,-3.2,1020.6,-21.4,0.0,NW,1.8,Huairou
3,4,2013,3,1,3,3.0,3.0,3.0,2.0,NaN,NaN,-3.3,1021.3,-23.7,0.0,NNW,2.4,Huairou
4,5,2013,3,1,4,3.0,3.0,7.0,NaN,300.0,86.0,-4.1,1022.1,-22.7,0.0,NNW,2.2,Huairou

(35064, 18)

## Comprehending Dataset Structure

Prior to carrying out preprocessing and merging procedures, it is crucial to comprehend the dataset structure, which was analysed to determine the number of records, column names, data kinds, and missing values.

In [25]:
# Dataset information

print("Dongsi Info")
dongsi.info()

print("\nGuanyuan Info")
guanyuan.info()

print("\nChangping Info")
changping.info()

print("\nHuairou Info")
huairou.info()

Dongsi Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34314 non-null  float64
 6   PM10     34511 non-null  float64
 7   SO2      34401 non-null  float64
 8   NO2      33463 non-null  float64
 9   CO       31867 non-null  float64
 10  O3       34400 non-null  float64
 11  TEMP     35044 non-null  float64
 12  PRES     35044 non-null  float64
 13  DEWP     35044 non-null  float64
 14  RAIN     35044 non-null  float64
 15  wd       34986 non-null  object
 16  WSPM     35050 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

Guanyuan Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34448 non-null  float64
 6   PM10     34635 non-null  float64
 7   SO2      34590 non-null  float64
 8   NO2      34405 non-null  float64
 9   CO       33311 non-null  float64
 10  O3       33891 non-null  float64
 11  TEMP     35044 non-null  float64
 12  PRES     35044 non-null  float64
 13  DEWP     35044 non-null  float64
 14  RAIN     35044 non-null  float64
 15  wd       34983 non-null  object
 16  WSPM     35050 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

Changping Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34290 non-null  float64
 6   PM10     34482 non-null  float64
 7   SO2      34436 non-null  float64
 8   NO2      34397 non-null  float64
 9   CO       33543 non-null  float64
 10  O3       34460 non-null  float64
 11  TEMP     35011 non-null  float64
 12  PRES     35014 non-null  float64
 13  DEWP     35011 non-null  float64
 14  RAIN     35013 non-null  float64
 15  wd       34924 non-null  object
 16  WSPM     35021 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

Huairou Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34111 non-null  float64
 6   PM10     34287 non-null  float64
 7   SO2      34084 non-null  float64
 8   NO2      33425 non-null  float64
 9   CO       33642 non-null  float64
 10  O3       33913 non-null  float64
 11  TEMP     35013 non-null  float64
 12  PRES     35011 non-null  float64
 13  DEWP     35011 non-null  float64
 14  RAIN     35009 non-null  float64
 15  wd       34762 non-null  object
 16  WSPM     35015 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

## Finding Missing Values

In order to assess the quality of the data and ascertain whether preprocessing methods would be necessary prior to analysis and predictive modelling, missing values were looked at.

In [26]:
# Missing values check

print("Dongsi Missing Values")
print(dongsi.isnull().sum())

print("\nGuanyuan Missing Values")
print(guanyuan.isnull().sum())

print("\nChangping Missing Values")
print(changping.isnull().sum())

print("\nHuairou Missing Values")
print(huairou.isnull().sum())

Dongsi Missing Values
No            0
year          0
month         0
day           0
hour          0
PM2.5       750
PM10        553
SO2         663
NO2        1601
CO         3197
O3          664
TEMP         20
PRES         20
DEWP         20
RAIN         20
wd           78
WSPM         14
station       0
dtype: int64

Guanyuan Missing Values
No            0
year          0
month         0
day           0
hour          0
PM2.5       616
PM10        429
SO2         474
NO2         659
CO         1753
O3         1173
TEMP         20
PRES         20
DEWP         20
RAIN         20
wd           81
WSPM         14
station       0
dtype: int64

Changping Missing Values
No            0
year          0
month         0
day           0
hour          0
PM2.5       774
PM10        582
SO2         628
NO2         667
CO         1521
O3          604
TEMP         53
PRES         50
DEWP         53
RAIN         51
wd          140
WSPM         43
station       0
dtype: int64

Huairou Missing Values
No            0
year          0
month         0
day           0
hour          0
PM2.5       953
PM10        777
SO2         980
NO2        1639
CO         1422
O3         1151
TEMP         51
PRES         53
DEWP         53
RAIN         55
wd          302
WSPM         49
station       0
dtype: int64

In [27]:
dongsi['station'] = 'Dongsi'
guanyuan['station'] = 'Guanyuan'
changping['station'] = 'Changping'
huairou['station'] = 'Huairou'

In [30]:
# Check duplicates

print("Duplicate Rows:")
print(air_quality.duplicated().sum())

Duplicate Rows:
0

In [31]:
# Remove duplicates if any

air_quality = air_quality.drop_duplicates()

In [32]:
air_quality['date'] = pd.to_datetime(
    air_quality[['year', 'month', 'day', 'hour']]
)

air_quality.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station,date
0,1,2013,3,1,0,9.0,9.0,3.0,17.0,300.0,89.0,-0.5,1024.5,-21.4,0.0,NNW,5.7,Dongsi,2013-03-01 00:00:00
1,2,2013,3,1,1,4.0,4.0,3.0,16.0,300.0,88.0,-0.7,1025.1,-22.1,0.0,NW,3.9,Dongsi,2013-03-01 01:00:00
2,3,2013,3,1,2,7.0,7.0,NaN,17.0,300.0,60.0,-1.2,1025.3,-24.6,0.0,NNW,5.3,Dongsi,2013-03-01 02:00:00
3,4,2013,3,1,3,3.0,3.0,5.0,18.0,NaN,NaN,-1.4,1026.2,-25.5,0.0,N,4.9,Dongsi,2013-03-01 03:00:00
4,5,2013,3,1,4,3.0,3.0,7.0,NaN,200.0,84.0,-1.9,1027.1,-24.5,0.0,NNW,3.2,Dongsi,2013-03-01 04:00:00

## Handling Timestamps

The year, month, day, and hour columns in the original dataset each contain temporal information separately. To enhance time-series analysis and streamline merging procedures, these columns were merged into a single datetime column using Pandas datetime capabilities.

In [33]:
def create_datetime(df):
    df['datetime'] = pd.to_datetime(
        df[['year', 'month', 'day', 'hour']]
    )
    return df

In [34]:
dongsi = create_datetime(dongsi)
guanyuan = create_datetime(guanyuan)
changping = create_datetime(changping)
huairou = create_datetime(huairou)

In [35]:
dongsi[['datetime']].head()

             datetime
0 2013-03-01 00:00:00
1 2013-03-01 01:00:00
2 2013-03-01 02:00:00
3 2013-03-01 03:00:00
4 2013-03-01 04:00:00

## Combining and Merging Certain Datasets

The Pandas concat() function was used to combine the four chosen datasets into a single, cohesive dataframe. Comparative study between urban and suburban monitoring stations is made possible by combining the datasets.

In [39]:
dongsi['station'] = 'Dongsi'
guanyuan['station'] = 'Guanyuan'
changping['station'] = 'Changping'
huairou['station'] = 'Huairou'

In [43]:
combined_df = pd.concat(
    [dongsi, guanyuan, changping, huairou],
    ignore_index=True
)

print("Merged Dataset Shape:")
print(air_quality.shape)

Merged Dataset Shape:
(140256, 19)

In [41]:
combined_df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station,datetime
0,1,2013,3,1,0,9.0,9.0,3.0,17.0,300.0,89.0,-0.5,1024.5,-21.4,0.0,NNW,5.7,Dongsi,2013-03-01 00:00:00
1,2,2013,3,1,1,4.0,4.0,3.0,16.0,300.0,88.0,-0.7,1025.1,-22.1,0.0,NW,3.9,Dongsi,2013-03-01 01:00:00
2,3,2013,3,1,2,7.0,7.0,NaN,17.0,300.0,60.0,-1.2,1025.3,-24.6,0.0,NNW,5.3,Dongsi,2013-03-01 02:00:00
3,4,2013,3,1,3,3.0,3.0,5.0,18.0,NaN,NaN,-1.4,1026.2,-25.5,0.0,N,4.9,Dongsi,2013-03-01 03:00:00
4,5,2013,3,1,4,3.0,3.0,7.0,NaN,200.0,84.0,-1.9,1027.1,-24.5,0.0,NNW,3.2,Dongsi,2013-03-01 04:00:00

In [42]:
combined_df.to_csv(
    'combined_air_quality.csv',
    index=False
)